### ISSUE TITLE
Add New Language Translations 2.5.2

### ISSUE THREAD

**Issue by john-lang-86** [john-lang-86/lj-maintenance-mode#6]
Pre-requisite #8

Add missing language translations for new strings added in the settings page in 2.5, 2.5.1 and 2.5.2.

... time to RTFM and learn 'PO Edit'.

- [x] Update source code to follow [translation best practice recommendations](https://codex.wordpress.org/I18n_for_WordPress_Developers).
    - [x] Use string format functions, not concatenation.
    - [x] Split at paragrahs, where possible. Not sentenances and not whole pages.
    - [x] Minimize slang and abbreviations.
    - [x] Remove most control characters.
    - [x] Remove URLs, unless it contains a language specific identifer that requires translation.
    - [x] Remove unnecessary whitespace characters.
- [x] Update source code to follow [lessons learnt from people who know better than me](http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/).
    - [x] No run-time or pharsing dependency.
    - [x] Phrases, not words.
    - [x] Add context for translators.
    - [x] Minimise the unnecessary markup.

**Observation 1:** Found the [maintenance mode plugin](https://translate.wordpress.org/projects/wp-plugins/lj-maintenance-mode/) official language pack site.

**Situation 1:** There is a clear note about ['be careful with machine translations'](https://make.wordpress.org/polyglots/handbook/translating/expectations/#be-careful-with-machine-translation) as they are generally not an acceptable practice and that they don't even want them to be submitted for review. Ok, good to know for the core language packs supported by the [official polyglots teams](https://make.wordpress.org/polyglots/teams/). So, I just won't submit any of this to them, in alignment with their desires.

**Conclusion 1:** Let's explore the quality of reverse translation and/or the PoEdit Translation Memory capability and/or the already translated terminology in the official WordPress core files (a small tweak to use their domain, could be an option, maybe?).

**Situation 2:** A [Kinsta article on Multilingual WordPress](https://kinsta.com/blog/wordpress-multilingual/) indicates there are 12 primary languages that should be included if we want to cover a large portion of the user community.
![kinsta-native-language-research](https://user-images.githubusercontent.com/97158287/158047571-7080c864-c1ca-450c-ac1e-935587352f59.jpg)

**Situation 3:** The [Stripe payment utility supports these languages](https://support.stripe.com/questions/supported-languages-for-stripe-checkout-and-payment-links). If a language has enough traffic and financial throughput then it should also have a lot of WordPress sites ... that need a localised 'Maintenance Mode' plugin in their language.   :-)

**Conclusion 3:** Let's make sure they are all covered, if possible.

**Situation 4:** As-at 26/01/2022, only [138 locales (language_region) of 205](https://make.wordpress.org/polyglots/teams/) have > 50% translation status.

**Conclusion 4:** Let's cross-reference against the [WordPress Statistics for Locales](https://wordpress.org/about/stats/) to align with locales that are actively contributing/translating ... allowing this activity to focus on the wider and active user communities.
1. Focus on installation statistics, in descending ranked order; then
2. Focus on up-to-date translations, which indicates an active community.

**Tip:** The PO and MO files should have the WordPress plugin slug as the file prefix ... `lj-maintenance-mode-en_US.po`.

**Tip:** PoEdit Pro uses DeepL service for pre-translation capability. Yes, please, this is what should be used.

**Tip:** Each .po file can leverage the 'Translation' -> 'Update from Source Code' menu option; when two configuration options are in place to be able to scan the PHP source code that is the WordPress plugin.
1. Navigate 'Translation' -> 'Properties' menu. Click on the 'Sources Paths' tab. Use the 'Paths' text area and its [+] button to enter the directory/folder where the WordPress source code is available to you.
2. Navigate 'Translation' -> 'Properties' menu. Click on the 'Sources Keywords' tab. Enter these 'Additional Keywords'.
    - __
    - _e
    - _n:1,2
    - _x:1,2c
    - _ex:1,2c
    - _nx:4c,1,2
    - esc_attr__
    - esc_attr_e
    - esc_attr_x:1,2c
    - esc_html__
    - esc_html_e
    - esc_html_x:1,2c 

**Situation 5:** The DeepL machine translations don't really like the sprintf( %s ) embedded approach, assuming this is because the %s is a technology injection for pre-processors to parse in a run-time environment, which really has nothing to do with locales (language_region) native language spoken as part of day-to-day living. 
While paragraphs are the recommended solution, seriously consider treating the %s like the markup recommendation (aka break it up into smaller translations)(???).

**Conclusion 5-1:** Ok, this approach (to remove the %s technology injections) has now been confirmed as a decent way forward. Way more of the pre-translation requests are coming back with a 100% completed list of translation values filled in. This first step of providing a pre-translation will make it a lot easier for a native speaker of each locale (language_region) to cast their eye over the pre-translations and spot where the online machine learning proposals were less than ideal.

**Conclusion 5-2:** Ok, the other approach to improve the pre-translation quality is to improve the _"Readability"_ of the original English. Seems like an obvious statement, but it was not something that initially stood out at the beginning of this pre-translation experiment. Services like www.grammarly.com and www.readable.com were helpful as a pre-requisite step to improve the original content before engaging the pre-translation service.

**Solution 6:** As-at 26/01/2022, this is the WordPress statistics for locales (language_region) installed.

- [x] `en_US` English (US)		44.08%
- [x] `es_ES` Spanish (Spain)		5.97%
- [x] `ja` Japanese			5.78%
- [x] `de_DE` German (Germany)			5.72%
- [x] `fr_FR` French (France)		4.27%
- [x] **Others               	   	3.96%**
- [x] `en_GB` English (UK)		3.63%
- [x] `it_IT` Italian (Italy)				3.15%
- [x] `pt_BR` Portuguese (Brazil)	2.97%
- [x] `ru_RU` Russian (Russia)			2.76%
- [x] `nl_NL` Dutch (Netherlands)				2.57%
- [x] `pl_PL` Polish (Poland)				1.95%
- [x] `tr_TR` Turkish (Turkey)			1.23%
- [x] `fa_IR` Persian (Iran)			0.90%
- [x] `zh_CN` Chinese (China)		0.87%
- [x] `vi` Vietnamese			0.78%
- [x] `en_AU` English (Australia)	0.78%
- [x] `pt_PT` Portuguese (Portugal)	0.71%
- [x] `sv_SE` Swedish (Sweden)			0.66%
- [x] `cs_CZ` Czech (Czech Republic)				0.61%
- [x] `id_ID` Indonesian (Indonesia)			0.52%
- [x] `da_DK` Danish (Denmark)				0.51%
- [x] `hu_HU` Hungarian (Hungary)			0.46%
- [x] `en_CA` English (Canada)		0.43%
- [x] `he_IL` Hebrew (Israel)			0.35%
- [x] `es_MX` Spanish (Mexico)	0.34%
- [x] `ar` Arabic				0.34%
- [x] `ro_RO` Romanian (Romania)			0.32%
- [x] `zh_TW` Chinese (Taiwan)	0.30%
- [x] `fi` Finnish				0.29%
- [x] `ko_KR` Korean (South Korea)	0.28%
- [x] `el` Greek				0.28%
- [x] `th` Thai				0.26%
- [x] `sk_SK` Slovak (Slovakia)				0.24%
- [x] `nb_NO` Norwegian Bokmål (Norway)		0.23%
- [x] `de_DE_formal` German (Formal)		0.20%
- [x] `en_ZA` English (South Africa)	0.19%
- [x] `de_CH` German (Switzerland)	0.14%
- [x] `bg_BG` Bulgarian (Bulgaria)			0.14%
- [x] `es_CL` Spanish (Chile)		0.14%
- [x] `es_AR` Spanish (Argentina)	0.13%
- [x] `ca` Catalan			0.13%
- [x] `uk` Ukrainian			0.13%
- [x] `es_CO` Spanish (Colombia)	0.12%
- [x] `hr` Croatian			0.10%
- [x] `lt_LT` Lithuanian (Lithuania)			0.10%

**Primary language.** The first part of a locale (language_region) that are part of the above list (installation statistics), but not directly identified.
- [x] `bg` Bulgarian
- [x] `zh` Chinese
- [x] `cs` Czech
- [x] `da` Danish
- [x] `nl` Dutch
- [x] `en` English
- [x] `fr` French
- [x] `de` German
- [x] `he` Hebrew
- [x] `hu` Hungarian
- [x] `id` Indonesian
- [x] `it` Italian
- [x] `ko` Korean
- [x] `lt` Lithuanian
- [x] `nb` Norwegian
- [x] `fa` Persian
- [x] `pl` Polish
- [x] `pt` Portuguese
- [x] `ro` Romanian
- [x] `ru` Russian
- [x] `sk` Slovak
- [x] `es` Spanish
- [x] `sv` Swedish
- [x] `tr` Turkish

**Solution 7:** As-at 06/02/2022, there are 42 locales (language_region) that have a [WordPress 5.9 100%](https://make.wordpress.org/polyglots/teams/#translated-100) translation status. These ones are not included in the above-prioritised lists and should be added as there is an active community.
- [x] `am` Amharic
- [x] `nl_BE` Dutch (Belgium)
- [x] `en_NZ` English (New Zealand)
- [x] `eo` Esperanto
- [x] `fr_CA` French (Canada)
- [x] `gl_ES` Galician (Spain)
- [x] `gl` Galician
- [x] `ka_GE` Georgian (Georgia)
- [x] `ka` Georgian
- [x] `de_AT` German (Austria)
- [x] `de_CH_informal` German (Switzerland, Informal)
- [x] `kn` Kannada
- [x] `lv` Latvian
- [x] `es_EC` Spanish (Ecuador)
- [x] `es_VE` Spanish (Venezuela)
- [x] `cy` Welsh

**Solution 8:** As-at 06/02/2022, there are 27 locales (language_region) that have a [WordPress 5.9 95%](https://make.wordpress.org/polyglots/teams/#translated-95) translation status. These ones are not included in the above-prioritised lists and should be added as there is an active community.
- [x] `sq` Albanian
- [x] `eu` Basque
- [x] `bs` Bosnian
- [x] `zh_HK` Chinese (Hong Kong)
- [x] `nl_NL_formal` Dutch (Formal)
- `kab` Kabyle ... DeepL service unable to pre-translate most strings.
- `ckb` Kurdish (Sorani) ... DeepL service does not offer this language for translation.
- `dsb` Lower Sorbian ... DeepL service unable to pre-translate most strings.
- [x] `fa_AF` Persian (Afghanistan)
- `pt_PT_ao90` Portuguese (Portugal, AO90) ... DeepL service does not offer this language for translation.
- `skr` Saraiki ... DeepL service does not offer this language for translation.
- [x] `es_CR` Spanish (Costa Rica)
- [x] `es_DO` Spanish (Dominican Republic)
- [x] `es_PE` Spanish (Peru)
- `hsb` Upper Sorbian ... DeepL service unable to pre-translate most strings.

**Solution 9:** As-at 06/02/2022, there are 11 locales (language_region) that have a [WordPress 5.9 90%](https://make.wordpress.org/polyglots/teams/#translated-90) translation status. These ones are not included in the above-prioritised lists and should be added as there is an active community.
- [x] `af` Afrikaans
- [x] `fr_BE` French (Belgium)
- [x] `sr_RS` Serbian (Cyrillic, Serbia)
- [x] `sl_SI` Slovenian (Slovenia)
- [x] `ur` Urdu
- [x] `pt_AO` Portuguese (Angola)
- [x] `sr` Serbian
- `snd` Sindhi ... DeepL service does not offer this language for translation.
- [x] `sl` Slovenian

**Solution 10:** As-at 27/03/2022, there are quite a few languages supported by the [Stripe financial payment processing service](https://support.stripe.com/questions/supported-languages-for-stripe-checkout-and-payment-links).
- [x] `bg` Bulgarian ... already included in the WordPress translations at 90% and above.
- [x] `hr` Croatian ... already included in the WordPress translations at 90% and above.
- [x] `cs` Czech ... already included in the WordPress translations at 90% and above.
- [x] `da` Danish ... already included in the WordPress translations at 90% and above.
- [x] `nl` Dutch ... already included in the WordPress translations at 90% and above.
- [x] `en` English ... already included in the WordPress translations at 90% and above.
- [x] `et` Estonian
- [x] `fi` Finnish ... already included in the WordPress translations at 90% and above.
- [x] `fil` Filipino
- [x] `fr` French ... already included in the WordPress translations at 90% and above.
- [x] `de` German ... already included in the WordPress translations at 90% and above.
- [x] `el` Greek ... already included in the WordPress translations at 90% and above.
- [x] `hu` Hungarian ... already included in the WordPress translations at 90% and above.
- [x] `id` Indonesian ... already included in the WordPress translations at 90% and above.
- [x] `it` Italian ... already included in the WordPress translations at 90% and above.
- [x] `ja` Japanese ... already included in the WordPress translations at 90% and above.
- [x] `ko` Korean ... already included in the WordPress translations at 90% and above.
- [x] `lv` Latvian ... already included in the WordPress translations at 90% and above.
- [x] `lt` Lithuanian ... already included in the WordPress translations at 90% and above.
- [x] `ms` Malay
- [x] `mt` Maltese
- [x] `nb` Norwegian Bokmål  ... already included in the WordPress translations at 90% and above.
- [x] `pl` Polish ... already included in the WordPress translations at 90% and above.
- [x] `pt` Portuguese ... already included in the WordPress translations at 90% and above.
- [x] `ro` Romanian ... already included in the WordPress translations at 90% and above.
- [x] `ru` Russian ... already included in the WordPress translations at 90% and above.
- [x] `zh` Simplified Chinese ... already included in the WordPress translations at 90% and above.
- [x] `sk` Slovak ... already included in the WordPress translations at 90% and above.
- [x] `sl` Slovenian ... already included in the WordPress translations at 90% and above.
- [x] `es` Spanish ... already included in the WordPress translations at 90% and above.
- [x] `sv` Swedish ... already included in the WordPress translations at 90% and above.
- [x] `th` Thai ... already included in the WordPress translations at 90% and above.
- [x] `tr` Turkish ... already included in the WordPress translations at 90% and above.
- [x] `vi` Vietnamese ... already included in the WordPress translations at 90% and above.

**Solution 11:** While these locales (language_region) were not prioritised for the above specific and targeted reasons, they have been done because the PoEdit applications pre-translate service did provide a complete set of translation responses. While this is not a good enough reason to ensure quality, it is good enough for this learning experiment in understanding the current state of pre-translation service capability, at a high level.

- [x] `hy` Armenian
- [x] `as` Assamese
- [x] `az` Azerbaijani
- [x] `be` Belarusian
- [x] `bn` Bengali
- [x] `my` Burmese
- [x] `yue` Cantonese
- [x] `gu` Gujarati
- [x] `ha` Hausa
- [x] `haw` Hawaiian
- [x] `hi` Hindi
- [x] `is` Icelandic
- [x] `ig` Igbo
- [x] `ga` Irish
- [x] `km` Khmer
- [x] `rw` Kinyarwanda
- [x] `ko_KP` Korean (North Korea)
- [x] `ky` Kyrgyz
- [x] `lao` Lao
- [x] `lb` Luxembourgish
- [x] `mk` Macedonian
- [x] `mg` Malagasy
- [x] `ml` Malayalam
- [x] `mr` Marathi
- [x] `mn` Mongolian
- [x] `ne` Nepali
- [x] `nn` Norwegian Nynorsk
- [x] `or` Oriya
- [x] `ps` Pashto
- [x] `pa` Punjabi
- [x] `gd` Scottish Gaelic
- [x] `so` Somali
- [x] `ta` Tamil
- [x] `bo` Tibetan
- [x] `to` Tongan
- [x] `uz` Uzbek
- [x] `yi` Yiddish
- [x] `zu` Zulu

**Comment by mpQadir** [comment]
Saraiki is an important language, so Saraiki language be added.

**Comment by john-lang-86** [comment]
> mpQadir

I've been unable to leverage the Google/DeepL translators for a few locales (language_region) and `skr` Saraiki is one of them. 

Here is the .pot file being used for the above documentation of my exploration in learning about .pot, .po and .mo files for WordPress plugins (with Po Edit Pro appication & services). With an intentional focus to understand how well the online translators have improved.
  
[lj-maintenance-mode.pot.zip](https://github.com/john-lang-86/lj-maintenance-mode/files/8103323/lj-maintenance-mode.pot.zip)

If you are able to assist with providing a `skr` Saraiki .po file before the [Milestone 2.5.2 due date on 28 March 2022](https://github.com/john-lang-86/lj-maintenance-mode/milestone/1) then it can be added to the 100+ languages to be submitted to the plugin author for review and inclusion.

**Comment by mpQadir** [comment]
Dear, Here are some files. For [Saraiki.po.zip](https://github.com/john-lang-86/lj-maintenance-mode/files/8104340/Saraiki.po.zip)

**Comment by john-lang-86** [comment]
Hi mpQadir, 
Thank you for the Saraiki zip file. 
There appears to be quite a lot of good effort put into these PO files for the core WordPress translation.

Unfortunately, I could not make much use of those files due to there being only a very small number of matching phrases to the ones in the updated Maintenance Mode plugin. I did start down the path of trying to put it together, like a jigsaw puzzle, by translating individual words into phrases but the result was patchy and still left quite a few phrases un-translated.

At this point, I'll be moving on from this specific language and leaving it to someone who is a native speaker of Saraiki to do the specific translation of the Maintenance Mode phrases.

Thanks again for providing the zip file to at least allow me the opportunity to see if it could be put together.
Kind regards,
John
